"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { BarChart3, Box, Globe2, ImageUp, LayoutDashboard, LoaderCircle, LogOut, MapPinned, PackageCheck, Pencil, Plus, RefreshCw, ShoppingBag, Trash2, Truck, Users, X } from "lucide-react";
import { money } from "@/lib/format";
import BrandLogo from "@/components/BrandLogo";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { adminSchema } from "@/lib/validations/admin";
import { productSchema } from "@/lib/validations/product";
import { settingsSchema } from "@/lib/validations/settings";
import { zoneSchema } from "@/lib/validations/zone";

type Product = { id: number; slug: string; name: string; category: string; description: string; price: number; stock: number; weight: string | null; active: boolean; featured: boolean; image: string };
type Zone = { id: number; name: string; fee: number; eta: string };
type Settings = { phoneDisplay: string; phoneHref: string; address: string; heroEyebrow: string; heroTitle: string; heroAccent: string; heroDescription: string; announcementOne: string; announcementTwo: string; announcementThree: string; contactTitle: string; contactDescription: string };
type Status = "NEW" | "CONFIRMED" | "PREPARING" | "DELIVERING" | "DELIVERED" | "CANCELLED";
type Order = { id: number; reference: string; customerName: string; phone: string; address: string; notes: string | null; status: Status; total: number; createdAt: Date | string; zone: { name: string }; items: { id: number; quantity: number; unitPrice: number; product: { name: string } }[] };
type Admin = { id: number; name: string; email: string; active: boolean; createdAt: Date | string };
type Tab = "dashboard" | "orders" | "products" | "zones" | "settings" | "admins";
const labels: Record<Status, string> = { NEW: "Nouvelle", CONFIRMED: "Confirmee", PREPARING: "Preparation", DELIVERING: "En livraison", DELIVERED: "Livree", CANCELLED: "Annulee" };
const statuses = Object.keys(labels) as Status[];
const emptyProduct = { slug: "", name: "", category: "Bouteilles", description: "", price: 0, stock: 0, weight: "", image: "", featured: false, active: true };

export default function AdminDashboard({ initialProducts, initialOrders, initialZones, initialSettings, initialAdmins, currentAdminId }: { initialProducts: Product[]; initialOrders: Order[]; initialZones: Zone[]; initialSettings: Settings; initialAdmins: Admin[]; currentAdminId: number }) {
  const [products, setProducts] = useState(initialProducts);
  const [orders, setOrders] = useState(initialOrders);
  const [zones, setZones] = useState(initialZones);
  const [settings, setSettings] = useState(initialSettings);
  const [admins, setAdmins] = useState(initialAdmins);
  const [tab, setTab] = useState<Tab>("dashboard");
  const [selected, setSelected] = useState<Order | null>(null);
  const [editing, setEditing] = useState<Partial<Product> | null>(null);
  const [zoneDraft, setZoneDraft] = useState({ name: "", fee: 0, eta: "" });
  const [adminDraft, setAdminDraft] = useState({ name: "", email: "", password: "" });
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");

  const stats = useMemo(() => ({ orders: orders.length, pending: orders.filter((order) => !["DELIVERED", "CANCELLED"].includes(order.status)).length, revenue: orders.filter((order) => order.status !== "CANCELLED").reduce((sum, order) => sum + order.total, 0), low: products.filter((product) => product.stock < 10).length }), [orders, products]);
  const title = { dashboard: "Vue generale", orders: "Commandes", products: "Catalogue", zones: "Zones de livraison", settings: "Informations du site", admins: "Administrateurs" }[tab];

  async function request(url: string, method: string, body?: unknown) {
    setBusy(url); setMessage("");
    const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const data = await response.json(); setBusy("");
    if (!response.ok) { setMessage(data.error ?? "Une erreur est survenue."); return null; }
    return data;
  }
  async function productPatch(id: number, data: Partial<Product>) { const updated = await request(`/api/admin/products/${id}`, "PATCH", data); if (updated) setProducts((current) => current.map((product) => product.id === id ? { ...product, ...updated } : product)); }
  async function productSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const updated = editing.id ? await request(`/api/admin/products/${editing.id}`, "PATCH", editing) : await request("/api/admin/products", "POST", editing); if (!updated) return; setProducts((current) => editing.id ? current.map((product) => product.id === editing.id ? updated : product) : [...current, updated]); setEditing(null); setMessage("Produit enregistre."); }
  async function productRemove(id: number) { const updated = await request(`/api/admin/products/${id}`, "DELETE"); if (updated) setProducts((current) => current.map((product) => product.id === id ? updated : product)); }
  async function orderPatch(id: number, status: Status) { const updated = await request(`/api/admin/orders/${id}`, "PATCH", { status }); if (updated) { setOrders((current) => current.map((order) => order.id === id ? { ...order, status: updated.status } : order)); setSelected((current) => current?.id === id ? { ...current, status: updated.status } : current); } }
  async function zoneSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const parsed = zoneSchema.safeParse(zoneDraft); if (!parsed.success) return setMessage(parsed.error.issues[0].message); const zone = await request("/api/admin/zones", "POST", parsed.data); if (zone) { setZones((current) => [...current, zone]); setZoneDraft({ name: "", fee: 0, eta: "" }); } }
  async function zonePatch(id: number, data: Partial<Zone>) { const zone = await request(`/api/admin/zones/${id}`, "PATCH", data); if (zone) setZones((current) => current.map((item) => item.id === id ? zone : item)); }
  async function zoneRemove(id: number) { const zone = await request(`/api/admin/zones/${id}`, "DELETE"); if (zone) setZones((current) => current.filter((item) => item.id !== id)); }
  async function settingsSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const parsed = settingsSchema.safeParse(settings); if (!parsed.success) return setMessage(parsed.error.issues[0].message); const updated = await request("/api/admin/settings", "PATCH", parsed.data); if (updated) { setSettings(updated); setMessage("Informations du site enregistrees."); } }
  async function adminSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const parsed = adminSchema.safeParse(adminDraft); if (!parsed.success) return setMessage(parsed.error.issues[0].message); const admin = await request("/api/admin/admins", "POST", parsed.data); if (admin) { setAdmins((current) => [...current, admin]); setAdminDraft({ name: "", email: "", password: "" }); setMessage("Administrateur ajoute."); } }
  async function adminRemove(id: number) { const result = await request(`/api/admin/admins/${id}`, "DELETE"); if (result) { setAdmins((current) => current.filter((admin) => admin.id !== id)); setMessage("Administrateur supprime."); } }

  return <main className="admin-shell">
    <aside className="admin-side"><Link href="/" className="brand"><BrandLogo compact /></Link><nav><Nav tab={tab} target="dashboard" setTab={setTab} icon={LayoutDashboard}>Vue generale</Nav><Nav tab={tab} target="orders" setTab={setTab} icon={ShoppingBag}>Commandes</Nav><Nav tab={tab} target="products" setTab={setTab} icon={Box}>Produits</Nav><Nav tab={tab} target="zones" setTab={setTab} icon={MapPinned}>Zones</Nav><Nav tab={tab} target="settings" setTab={setTab} icon={Globe2}>Site</Nav><Nav tab={tab} target="admins" setTab={setTab} icon={Users}>Administrateurs</Nav></nav><form action="/api/auth/logout" method="post"><Button type="submit" className="admin-logout"><LogOut /> Deconnexion</Button></form></aside>
    <section className="admin-main"><header><div><p>Espace administrateur</p><h1>{title}</h1></div><a href="/" target="_blank">Voir la boutique</a></header>{message ? <p className="admin-message">{message}</p> : null}
      {tab === "dashboard" ? <><div className="stat-grid"><Stat icon={ShoppingBag} label="Commandes" value={String(stats.orders)} /><Stat icon={Truck} label="A traiter" value={String(stats.pending)} /><Stat icon={BarChart3} label="CA commandes" value={money(stats.revenue)} /><Stat icon={PackageCheck} label="Stocks faibles" value={String(stats.low)} /></div><Panel kicker="Activite recente" title="Dernieres commandes"><Orders orders={orders.slice(0, 8)} setSelected={setSelected} busy={busy} patch={orderPatch} /></Panel></> : null}
      {tab === "orders" ? <Panel kicker="Suivi logistique" title="Toutes les commandes"><Orders orders={orders} setSelected={setSelected} busy={busy} patch={orderPatch} /></Panel> : null}
      {tab === "products" ? <Panel kicker="Gestion du catalogue" title="Produits affiches en boutique" action={<Button onClick={() => setEditing(emptyProduct)}><Plus /> Ajouter</Button>}><div className="product-admin-list">{products.map((product) => <div className="product-admin expanded" key={product.id}><div className="admin-product-image"><Image src={product.image} alt="" fill className="object-contain" sizes="60px" /></div><div><b>{product.name}</b><small>{product.category} · {money(product.price)} · {product.active ? "Visible" : "Masque"}</small></div><Label>Stock<Input type="number" min="0" value={product.stock} onChange={(event) => setProducts((current) => current.map((item) => item.id === product.id ? { ...item, stock: Number(event.target.value) } : item))} onBlur={(event) => productPatch(product.id, { stock: Number(event.target.value) })} /></Label><Label className="switch-label"><Checkbox className="admin-checkbox" checked={product.featured} onCheckedChange={(checked) => productPatch(product.id, { featured: checked === true })} /> Populaire</Label><Label className="switch-label"><Checkbox className="admin-checkbox" checked={product.active} onCheckedChange={(checked) => productPatch(product.id, { active: checked === true })} /> Visible</Label><Button variant="outline" size="icon" className="icon-action" onClick={() => setEditing(product)}><Pencil /></Button><Button variant="outline" size="icon" className="icon-action danger" onClick={() => productRemove(product.id)}><Trash2 /></Button>{busy.includes(`/products/${product.id}`) ? <RefreshCw className="spin" /> : null}</div>)}</div></Panel> : null}
      {tab === "zones" ? <Panel kicker="Livraison" title="Zones et tarifs"><form className="admin-inline-form" onSubmit={zoneSave}><Input required placeholder="Nom de zone" value={zoneDraft.name} onChange={(e) => setZoneDraft({ ...zoneDraft, name: e.target.value })} /><Input required type="number" min="0" placeholder="Frais FCFA" value={zoneDraft.fee} onChange={(e) => setZoneDraft({ ...zoneDraft, fee: Number(e.target.value) })} /><Input required placeholder="Delai: 30 - 45 min" value={zoneDraft.eta} onChange={(e) => setZoneDraft({ ...zoneDraft, eta: e.target.value })} /><Button type="submit"><Plus /> Ajouter</Button></form><div className="zone-admin-list">{zones.map((zone) => <div key={zone.id}><Input value={zone.name} onChange={(e) => setZones((current) => current.map((item) => item.id === zone.id ? { ...item, name: e.target.value } : item))} onBlur={(e) => zonePatch(zone.id, { name: e.target.value })} /><Input type="number" value={zone.fee} onChange={(e) => setZones((current) => current.map((item) => item.id === zone.id ? { ...item, fee: Number(e.target.value) } : item))} onBlur={(e) => zonePatch(zone.id, { fee: Number(e.target.value) })} /><Input value={zone.eta} onChange={(e) => setZones((current) => current.map((item) => item.id === zone.id ? { ...item, eta: e.target.value } : item))} onBlur={(e) => zonePatch(zone.id, { eta: e.target.value })} /><Button variant="outline" size="icon" className="icon-action danger" onClick={() => zoneRemove(zone.id)}><Trash2 /></Button></div>)}</div></Panel> : null}
      {tab === "settings" ? <Panel kicker="Contenu editable" title="Informations commerciales du site"><form className="admin-settings-form" onSubmit={settingsSave}><Field label="Telephone affiche" value={settings.phoneDisplay} set={(value) => setSettings({ ...settings, phoneDisplay: value })} /><Field label="Telephone pour les liens" value={settings.phoneHref} set={(value) => setSettings({ ...settings, phoneHref: value })} /><Field label="Adresse commerciale" value={settings.address} set={(value) => setSettings({ ...settings, address: value })} wide /><Field label="Sur-titre du hero" value={settings.heroEyebrow} set={(value) => setSettings({ ...settings, heroEyebrow: value })} /><Field label="Titre du hero" value={settings.heroTitle} set={(value) => setSettings({ ...settings, heroTitle: value })} /><Field label="Accent du hero" value={settings.heroAccent} set={(value) => setSettings({ ...settings, heroAccent: value })} /><Field label="Description du hero" value={settings.heroDescription} set={(value) => setSettings({ ...settings, heroDescription: value })} wide area /><Field label="Annonce 1" value={settings.announcementOne} set={(value) => setSettings({ ...settings, announcementOne: value })} /><Field label="Annonce 2" value={settings.announcementTwo} set={(value) => setSettings({ ...settings, announcementTwo: value })} /><Field label="Annonce 3" value={settings.announcementThree} set={(value) => setSettings({ ...settings, announcementThree: value })} /><Field label="Titre contact" value={settings.contactTitle} set={(value) => setSettings({ ...settings, contactTitle: value })} /><Field label="Description contact" value={settings.contactDescription} set={(value) => setSettings({ ...settings, contactDescription: value })} wide /><Button type="submit" className="admin-primary">Enregistrer les informations</Button></form></Panel> : null}
      {tab === "admins" ? <Panel kicker="Acces au tableau de bord" title="Comptes administrateurs"><form className="admin-inline-form admin-user-form" onSubmit={adminSave}><Input required placeholder="Nom complet" value={adminDraft.name} onChange={(e) => setAdminDraft({ ...adminDraft, name: e.target.value })} /><Input required type="email" placeholder="email@exemple.sn" value={adminDraft.email} onChange={(e) => setAdminDraft({ ...adminDraft, email: e.target.value })} /><Input required type="password" minLength={8} placeholder="Mot de passe (8 caracteres min.)" value={adminDraft.password} onChange={(e) => setAdminDraft({ ...adminDraft, password: e.target.value })} /><Button type="submit"><Plus /> Ajouter</Button></form><div className="admin-user-list">{admins.map((admin) => <div key={admin.id}><div><b>{admin.name}</b><small>{admin.email}{admin.id === currentAdminId ? " · Votre compte" : ""}</small></div><span>{new Date(admin.createdAt).toLocaleDateString("fr-FR")}</span><Button variant="outline" size="icon" disabled={admin.id === currentAdminId} className="icon-action danger" onClick={() => adminRemove(admin.id)} title={admin.id === currentAdminId ? "Vous ne pouvez pas supprimer votre propre compte" : "Supprimer"}><Trash2 /></Button></div>)}</div></Panel> : null}
    </section>
    {editing ? <ProductEditor product={editing} setProduct={setEditing} close={() => setEditing(null)} submit={productSave} /> : null}
    {selected ? <OrderDetails selected={selected} close={() => setSelected(null)} /> : null}
  </main>;
}

function Nav({ tab, target, setTab, icon: Icon, children }: { tab: Tab; target: Tab; setTab: (tab: Tab) => void; icon: typeof Box; children: React.ReactNode }) { return <Button className={`admin-nav-item${tab === target ? " active" : ""}`} onClick={() => setTab(target)}><Icon /> <span>{children}</span></Button>; }
function Panel({ kicker, title, action, children }: { kicker: string; title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="admin-panel"><div className="panel-title"><div><p>{kicker}</p><h2>{title}</h2></div>{action}</div>{children}</section>; }
function Field({ label, value, set, wide, area, error }: { label: string; value: string; set: (value: string) => void; wide?: boolean; area?: boolean; error?: string }) { return <Label className={`admin-form-field${wide ? " wide-field" : ""}`}>{label}{area ? <Textarea aria-invalid={Boolean(error)} value={value} onChange={(e) => set(e.target.value)} /> : <Input aria-invalid={Boolean(error)} value={value} onChange={(e) => set(e.target.value)} />}{error ? <em>{error}</em> : null}</Label>; }
function ProductEditor({ product, setProduct, close, submit }: { product: Partial<Product>; setProduct: (product: Partial<Product>) => void; close: () => void; submit: (event: React.FormEvent<HTMLFormElement>) => void }) {
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState("");
  const [errors, setErrors] = useState<Record<string, string | undefined>>({});

  async function upload(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    setUploading(true); setUploadError("");
    const body = new FormData(); body.append("file", file);
    const response = await fetch("/api/admin/uploads/products", { method: "POST", body });
    const data = await response.json(); setUploading(false);
    if (!response.ok) return setUploadError(data.error ?? "Impossible d'envoyer cette image.");
    setProduct({ ...product, image: data.path });
  }

  function validate(event: React.FormEvent<HTMLFormElement>) {
    const result = productSchema.safeParse(product);
    if (result.success) { setErrors({}); return submit(event); }
    event.preventDefault();
    setErrors(Object.fromEntries(Object.entries(result.error.flatten().fieldErrors).map(([key, messages]) => [key, messages?.[0]])));
  }

  return <div className="admin-order-modal"><form className="product-editor" onSubmit={validate}><Button type="button" variant="ghost" size="icon" className="modal-x" onClick={close}><X /></Button><p>{product.id ? "Modifier le produit" : "Nouveau produit"}</p><h2>{product.name || "Produit boutique"}</h2><Field label="Nom" error={errors.name} value={product.name ?? ""} set={(value) => setProduct({ ...product, name: value })} /><Field label="Slug unique" error={errors.slug} value={product.slug ?? ""} set={(value) => setProduct({ ...product, slug: value })} /><Field label="Categorie" error={errors.category} value={product.category ?? ""} set={(value) => setProduct({ ...product, category: value })} /><Field label="Poids" value={product.weight ?? ""} set={(value) => setProduct({ ...product, weight: value })} /><Label className="admin-form-field">Prix FCFA<Input aria-invalid={Boolean(errors.price)} type="number" min="0" value={product.price ?? 0} onChange={(e) => setProduct({ ...product, price: Number(e.target.value) })} />{errors.price ? <em>{errors.price}</em> : null}</Label><Label className="admin-form-field">Stock<Input aria-invalid={Boolean(errors.stock)} type="number" min="0" value={product.stock ?? 0} onChange={(e) => setProduct({ ...product, stock: Number(e.target.value) })} />{errors.stock ? <em>{errors.stock}</em> : null}</Label><div className="product-uploader wide-field">{product.image ? <div className="upload-preview"><Image src={product.image} alt="" fill sizes="72px" className="object-contain" /></div> : <span className="upload-placeholder"><ImageUp /></span>}<div><b>Image du produit</b><small>JPG, PNG ou WEBP · 5 Mo maximum</small><Label className="upload-trigger">{uploading ? <LoaderCircle className="spin" /> : <ImageUp />}{uploading ? "Envoi..." : product.image ? "Remplacer l'image" : "Choisir une image"}<Input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading} /></Label>{uploadError || errors.image ? <em>{uploadError || errors.image}</em> : null}</div></div><Field label="Description" error={errors.description} value={product.description ?? ""} set={(value) => setProduct({ ...product, description: value })} wide area /><div className="product-options wide-field"><Label><Checkbox className="admin-checkbox" checked={product.featured ?? false} onCheckedChange={(checked) => setProduct({ ...product, featured: checked === true })} /><span><b>Populaire</b><small>Mettre le produit en avant</small></span></Label><Label><Checkbox className="admin-checkbox" checked={product.active ?? true} onCheckedChange={(checked) => setProduct({ ...product, active: checked === true })} /><span><b>Visible</b><small>Afficher dans la boutique</small></span></Label></div><div className="product-editor-actions"><Button type="submit" disabled={uploading} className="product-save-button">Enregistrer le produit</Button></div></form></div>;
}
function OrderDetails({ selected, close }: { selected: Order; close: () => void }) { return <div className="admin-order-modal"><div><Button variant="ghost" size="icon" onClick={close}>×</Button><p>{selected.reference}</p><h2>{selected.customerName}</h2><small>{selected.phone} · {selected.zone.name}</small><address>{selected.address}</address>{selected.notes ? <i>{selected.notes}</i> : null}<div className="modal-order-lines">{selected.items.map((item) => <div key={item.id}><span>{item.quantity} × {item.product.name}</span><b>{money(item.quantity * item.unitPrice)}</b></div>)}</div><strong>{money(selected.total)}</strong></div></div>; }
function Stat({ icon: Icon, label, value }: { icon: typeof ShoppingBag; label: string; value: string }) { return <article className="stat-card"><Icon /><p>{label}</p><b>{value}</b></article>; }
function Orders({ orders, setSelected, busy, patch }: { orders: Order[]; setSelected: (order: Order) => void; busy: string; patch: (id: number, status: Status) => void }) { return <div className="orders-table">{orders.length ? orders.map((order) => <div className="order-row" key={order.id}><Button variant="ghost" className="order-ref" onClick={() => setSelected(order)}><b>{order.reference}</b><small>{new Date(order.createdAt).toLocaleDateString("fr-FR")} · {order.customerName}</small></Button><span>{order.zone.name}</span><b>{money(order.total)}</b><Select value={order.status} onValueChange={(value) => patch(order.id, value as Status)} disabled={busy.includes(`/orders/${order.id}`)}><SelectTrigger className={`status admin-status-trigger ${order.status.toLowerCase()}`}><SelectValue /></SelectTrigger><SelectContent className="admin-select-content">{statuses.map((status) => <SelectItem className="admin-select-item" key={status} value={status}>{labels[status]}</SelectItem>)}</SelectContent></Select></div>) : <p className="admin-empty">Aucune commande pour le moment.</p>}</div>; }
