"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { BarChart3, Box, Globe2, LayoutDashboard, LogOut, MapPinned, PackageCheck, Pencil, Plus, RefreshCw, ShoppingBag, Trash2, Truck, Users, X } from "lucide-react";
import { money } from "@/lib/format";
import BrandLogo from "@/components/BrandLogo";

type Product = { id: number; slug: string; name: string; category: string; description: string; price: number; stock: number; weight: string | null; active: boolean; featured: boolean; image: string };
type Zone = { id: number; name: string; fee: number; eta: string };
type Settings = { phoneDisplay: string; phoneHref: string; address: string; heroEyebrow: string; heroTitle: string; heroAccent: string; heroDescription: string; announcementOne: string; announcementTwo: string; announcementThree: string; contactTitle: string; contactDescription: string };
type Status = "NEW" | "CONFIRMED" | "PREPARING" | "DELIVERING" | "DELIVERED" | "CANCELLED";
type Order = { id: number; reference: string; customerName: string; phone: string; address: string; notes: string | null; status: Status; total: number; createdAt: Date | string; zone: { name: string }; items: { id: number; quantity: number; unitPrice: number; product: { name: string } }[] };
type Admin = { id: number; name: string; email: string; active: boolean; createdAt: Date | string };
type Tab = "dashboard" | "orders" | "products" | "zones" | "settings" | "admins";
const labels: Record<Status, string> = { NEW: "Nouvelle", CONFIRMED: "Confirmee", PREPARING: "Preparation", DELIVERING: "En livraison", DELIVERED: "Livree", CANCELLED: "Annulee" };
const statuses = Object.keys(labels) as Status[];
const emptyProduct = { slug: "", name: "", category: "Bouteilles", description: "", price: 0, stock: 0, weight: "", image: "/images/topenergies/products/", featured: false, active: true };

export default function AdminDashboard({ initialProducts, initialOrders, initialZones, initialSettings, initialAdmins, currentAdminId }: { initialProducts: Product[]; initialOrders: Order[]; initialZones: Zone[]; initialSettings: Settings; initialAdmins: Admin[]; currentAdminId: number }) {
  const [products, setProducts] = useState(initialProducts);
  const [orders, setOrders] = useState(initialOrders);
  const [zones, setZones] = useState(initialZones);
  const [settings, setSettings] = useState(initialSettings);
  const [admins, setAdmins] = useState(initialAdmins);
  const [tab, setTab] = useState<Tab>("dashboard");
  const [selected, setSelected] = useState<Order | null>(null);
  const [editing, setEditing] = useState<Partial<Product> | null>(null);
  const [zoneDraft, setZoneDraft] = useState({ name: "", fee: 0, eta: "" });
  const [adminDraft, setAdminDraft] = useState({ name: "", email: "", password: "" });
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");

  const stats = useMemo(() => ({ orders: orders.length, pending: orders.filter((order) => !["DELIVERED", "CANCELLED"].includes(order.status)).length, revenue: orders.filter((order) => order.status !== "CANCELLED").reduce((sum, order) => sum + order.total, 0), low: products.filter((product) => product.stock < 10).length }), [orders, products]);
  const title = { dashboard: "Vue generale", orders: "Commandes", products: "Catalogue", zones: "Zones de livraison", settings: "Informations du site", admins: "Administrateurs" }[tab];

  async function request(url: string, method: string, body?: unknown) {
    setBusy(url); setMessage("");
    const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const data = await response.json(); setBusy("");
    if (!response.ok) { setMessage(data.error ?? "Une erreur est survenue."); return null; }
    return data;
  }
  async function productPatch(id: number, data: Partial<Product>) { const updated = await request(`/api/admin/products/${id}`, "PATCH", data); if (updated) setProducts((current) => current.map((product) => product.id === id ? { ...product, ...updated } : product)); }
  async function productSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const updated = editing.id ? await request(`/api/admin/products/${editing.id}`, "PATCH", editing) : await request("/api/admin/products", "POST", editing); if (!updated) return; setProducts((current) => editing.id ? current.map((product) => product.id === editing.id ? updated : product) : [...current, updated]); setEditing(null); setMessage("Produit enregistre."); }
  async function productRemove(id: number) { const updated = await request(`/api/admin/products/${id}`, "DELETE"); if (updated) setProducts((current) => current.map((product) => product.id === id ? updated : product)); }
  async function orderPatch(id: number, status: Status) { const updated = await request(`/api/admin/orders/${id}`, "PATCH", { status }); if (updated) { setOrders((current) => current.map((order) => order.id === id ? { ...order, status: updated.status } : order)); setSelected((current) => current?.id === id ? { ...current, status: updated.status } : current); } }
  async function zoneSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const zone = await request("/api/admin/zones", "POST", zoneDraft); if (zone) { setZones((current) => [...current, zone]); setZoneDraft({ name: "", fee: 0, eta: "" }); } }
  async function zonePatch(id: number, data: Partial<Zone>) { const zone = await request(`/api/admin/zones/${id}`, "PATCH", data); if (zone) setZones((current) => current.map((item) => item.id === id ? zone : item)); }
  async function zoneRemove(id: number) { const zone = await request(`/api/admin/zones/${id}`, "DELETE"); if (zone) setZones((current) => current.filter((item) => item.id !== id)); }
  async function settingsSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const updated = await request("/api/admin/settings", "PATCH", settings); if (updated) { setSettings(updated); setMessage("Informations du site enregistrees."); } }
  async function adminSave(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const admin = await request("/api/admin/admins", "POST", adminDraft); if (admin) { setAdmins((current) => [...current, admin]); setAdminDraft({ name: "", email: "", password: "" }); setMessage("Administrateur ajoute."); } }
  async function adminRemove(id: number) { const result = await request(`/api/admin/admins/${id}`, "DELETE"); if (result) { setAdmins((current) => current.filter((admin) => admin.id !== id)); setMessage("Administrateur supprime."); } }

  return <main className="admin-shell">
    <aside className="admin-side"><Link href="/" className="brand"><BrandLogo compact /></Link><nav><Nav tab={tab} target="dashboard" setTab={setTab} icon={LayoutDashboard}>Vue generale</Nav><Nav tab={tab} target="orders" setTab={setTab} icon={ShoppingBag}>Commandes</Nav><Nav tab={tab} target="products" setTab={setTab} icon={Box}>Produits</Nav><Nav tab={tab} target="zones" setTab={setTab} icon={MapPinned}>Zones</Nav><Nav tab={tab} target="settings" setTab={setTab} icon={Globe2}>Site</Nav><Nav tab={tab} target="admins" setTab={setTab} icon={Users}>Administrateurs</Nav></nav><form action="/api/auth/logout" method="post"><button><LogOut /> Deconnexion</button></form></aside>
    <section className="admin-main"><header><div><p>Espace administrateur</p><h1>{title}</h1></div><a href="/" target="_blank">Voir la boutique</a></header>{message ? <p className="admin-message">{message}</p> : null}
      {tab === "dashboard" ? <><div className="stat-grid"><Stat icon={ShoppingBag} label="Commandes" value={String(stats.orders)} /><Stat icon={Truck} label="A traiter" value={String(stats.pending)} /><Stat icon={BarChart3} label="CA commandes" value={money(stats.revenue)} /><Stat icon={PackageCheck} label="Stocks faibles" value={String(stats.low)} /></div><Panel kicker="Activite recente" title="Dernieres commandes"><Orders orders={orders.slice(0, 8)} setSelected={setSelected} busy={busy} patch={orderPatch} /></Panel></> : null}
      {tab === "orders" ? <Panel kicker="Suivi logistique" title="Toutes les commandes"><Orders orders={orders} setSelected={setSelected} busy={busy} patch={orderPatch} /></Panel> : null}
      {tab === "products" ? <Panel kicker="Gestion du catalogue" title="Produits affiches en boutique" action={<button onClick={() => setEditing(emptyProduct)}><Plus /> Ajouter</button>}><div className="product-admin-list">{products.map((product) => <div className="product-admin expanded" key={product.id}><div className="admin-product-image"><Image src={product.image} alt="" fill className="object-contain" sizes="60px" /></div><div><b>{product.name}</b><small>{product.category} · {money(product.price)} · {product.active ? "Visible" : "Masque"}</small></div><label>Stock<input type="number" min="0" value={product.stock} onChange={(event) => setProducts((current) => current.map((item) => item.id === product.id ? { ...item, stock: Number(event.target.value) } : item))} onBlur={(event) => productPatch(product.id, { stock: Number(event.target.value) })} /></label><label className="switch-label"><input type="checkbox" checked={product.featured} onChange={(event) => productPatch(product.id, { featured: event.target.checked })} /> Populaire</label><label className="switch-label"><input type="checkbox" checked={product.active} onChange={(event) => productPatch(product.id, { active: event.target.checked })} /> Visible</label><button className="icon-action" onClick={() => setEditing(product)}><Pencil /></button><button className="icon-action danger" onClick={() => productRemove(product.id)}><Trash2 /></button>{busy.includes(`/products/${product.id}`) ? <RefreshCw className="spin" /> : null}</div>)}</div></Panel> : null}
      {tab === "zones" ? <Panel kicker="Livraison" title="Zones et tarifs"><form className="admin-inline-form" onSubmit={zoneSave}><input required placeholder="Nom de zone" value={zoneDraft.name} onChange={(e) => setZoneDraft({ ...zoneDraft, name: e.target.value })} /><input required type="number" min="0" placeholder="Frais FCFA" value={zoneDraft.fee} onChange={(e) => setZoneDraft({ ...zoneDraft, fee: Number(e.target.value) })} /><input required placeholder="Delai: 30 - 45 min" value={zoneDraft.eta} onChange={(e) => setZoneDraft({ ...zoneDraft, eta: e.target.value })} /><button><Plus /> Ajouter</button></form><div className="zone-admin-list">{zones.map((zone) => <div key={zone.id}><input value={zone.name} onChange={(e) => setZones((current) => current.map((item) => item.id === zone.id ? { ...item, name: e.target.value } : item))} onBlur={(e) => zonePatch(zone.id, { name: e.target.value })} /><input type="number" value={zone.fee} onChange={(e) => setZones((current) => current.map((item) => item.id === zone.id ? { ...item, fee: Number(e.target.value) } : item))} onBlur={(e) => zonePatch(zone.id, { fee: Number(e.target.value) })} /><input value={zone.eta} onChange={(e) => setZones((current) => current.map((item) => item.id === zone.id ? { ...item, eta: e.target.value } : item))} onBlur={(e) => zonePatch(zone.id, { eta: e.target.value })} /><button className="icon-action danger" onClick={() => zoneRemove(zone.id)}><Trash2 /></button></div>)}</div></Panel> : null}
      {tab === "settings" ? <Panel kicker="Contenu editable" title="Informations commerciales du site"><form className="admin-settings-form" onSubmit={settingsSave}><Field label="Telephone affiche" value={settings.phoneDisplay} set={(value) => setSettings({ ...settings, phoneDisplay: value })} /><Field label="Telephone pour les liens" value={settings.phoneHref} set={(value) => setSettings({ ...settings, phoneHref: value })} /><Field label="Adresse commerciale" value={settings.address} set={(value) => setSettings({ ...settings, address: value })} wide /><Field label="Sur-titre du hero" value={settings.heroEyebrow} set={(value) => setSettings({ ...settings, heroEyebrow: value })} /><Field label="Titre du hero" value={settings.heroTitle} set={(value) => setSettings({ ...settings, heroTitle: value })} /><Field label="Accent du hero" value={settings.heroAccent} set={(value) => setSettings({ ...settings, heroAccent: value })} /><Field label="Description du hero" value={settings.heroDescription} set={(value) => setSettings({ ...settings, heroDescription: value })} wide area /><Field label="Annonce 1" value={settings.announcementOne} set={(value) => setSettings({ ...settings, announcementOne: value })} /><Field label="Annonce 2" value={settings.announcementTwo} set={(value) => setSettings({ ...settings, announcementTwo: value })} /><Field label="Annonce 3" value={settings.announcementThree} set={(value) => setSettings({ ...settings, announcementThree: value })} /><Field label="Titre contact" value={settings.contactTitle} set={(value) => setSettings({ ...settings, contactTitle: value })} /><Field label="Description contact" value={settings.contactDescription} set={(value) => setSettings({ ...settings, contactDescription: value })} wide /><button className="admin-primary">Enregistrer les informations</button></form></Panel> : null}
      {tab === "admins" ? <Panel kicker="Acces au tableau de bord" title="Comptes administrateurs"><form className="admin-inline-form admin-user-form" onSubmit={adminSave}><input required placeholder="Nom complet" value={adminDraft.name} onChange={(e) => setAdminDraft({ ...adminDraft, name: e.target.value })} /><input required type="email" placeholder="email@exemple.sn" value={adminDraft.email} onChange={(e) => setAdminDraft({ ...adminDraft, email: e.target.value })} /><input required type="password" minLength={8} placeholder="Mot de passe (8 caracteres min.)" value={adminDraft.password} onChange={(e) => setAdminDraft({ ...adminDraft, password: e.target.value })} /><button><Plus /> Ajouter</button></form><div className="admin-user-list">{admins.map((admin) => <div key={admin.id}><div><b>{admin.name}</b><small>{admin.email}{admin.id === currentAdminId ? " · Votre compte" : ""}</small></div><span>{new Date(admin.createdAt).toLocaleDateString("fr-FR")}</span><button disabled={admin.id === currentAdminId} className="icon-action danger" onClick={() => adminRemove(admin.id)} title={admin.id === currentAdminId ? "Vous ne pouvez pas supprimer votre propre compte" : "Supprimer"}><Trash2 /></button></div>)}</div></Panel> : null}
    </section>
    {editing ? <ProductEditor product={editing} setProduct={setEditing} close={() => setEditing(null)} submit={productSave} /> : null}
    {selected ? <OrderDetails selected={selected} close={() => setSelected(null)} /> : null}
  </main>;
}

function Nav({ tab, target, setTab, icon: Icon, children }: { tab: Tab; target: Tab; setTab: (tab: Tab) => void; icon: typeof Box; children: React.ReactNode }) { return <button className={tab === target ? "active" : ""} onClick={() => setTab(target)}><Icon /> {children}</button>; }
function Panel({ kicker, title, action, children }: { kicker: string; title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="admin-panel"><div className="panel-title"><div><p>{kicker}</p><h2>{title}</h2></div>{action}</div>{children}</section>; }
function Field({ label, value, set, wide, area }: { label: string; value: string; set: (value: string) => void; wide?: boolean; area?: boolean }) { return <label className={wide ? "wide-field" : ""}>{label}{area ? <textarea value={value} onChange={(e) => set(e.target.value)} /> : <input value={value} onChange={(e) => set(e.target.value)} />}</label>; }
function ProductEditor({ product, setProduct, close, submit }: { product: Partial<Product>; setProduct: (product: Partial<Product>) => void; close: () => void; submit: (event: React.FormEvent<HTMLFormElement>) => void }) { return <div className="admin-order-modal"><form className="product-editor" onSubmit={submit}><button type="button" className="modal-x" onClick={close}><X /></button><p>{product.id ? "Modifier le produit" : "Nouveau produit"}</p><h2>{product.name || "Produit boutique"}</h2><Field label="Nom" value={product.name ?? ""} set={(value) => setProduct({ ...product, name: value })} /><Field label="Slug unique" value={product.slug ?? ""} set={(value) => setProduct({ ...product, slug: value })} /><Field label="Categorie" value={product.category ?? ""} set={(value) => setProduct({ ...product, category: value })} /><Field label="Poids" value={product.weight ?? ""} set={(value) => setProduct({ ...product, weight: value })} /><label>Prix FCFA<input type="number" min="0" value={product.price ?? 0} onChange={(e) => setProduct({ ...product, price: Number(e.target.value) })} /></label><label>Stock<input type="number" min="0" value={product.stock ?? 0} onChange={(e) => setProduct({ ...product, stock: Number(e.target.value) })} /></label><Field label="Chemin ou URL image" value={product.image ?? ""} set={(value) => setProduct({ ...product, image: value })} wide /><Field label="Description" value={product.description ?? ""} set={(value) => setProduct({ ...product, description: value })} wide area /><label className="switch-label"><input type="checkbox" checked={product.featured ?? false} onChange={(e) => setProduct({ ...product, featured: e.target.checked })} /> Populaire</label><label className="switch-label"><input type="checkbox" checked={product.active ?? true} onChange={(e) => setProduct({ ...product, active: e.target.checked })} /> Visible</label><button className="admin-primary wide-field">Enregistrer le produit</button></form></div>; }
function OrderDetails({ selected, close }: { selected: Order; close: () => void }) { return <div className="admin-order-modal"><div><button onClick={close}>×</button><p>{selected.reference}</p><h2>{selected.customerName}</h2><small>{selected.phone} · {selected.zone.name}</small><address>{selected.address}</address>{selected.notes ? <i>{selected.notes}</i> : null}<div className="modal-order-lines">{selected.items.map((item) => <div key={item.id}><span>{item.quantity} × {item.product.name}</span><b>{money(item.quantity * item.unitPrice)}</b></div>)}</div><strong>{money(selected.total)}</strong></div></div>; }
function Stat({ icon: Icon, label, value }: { icon: typeof ShoppingBag; label: string; value: string }) { return <article className="stat-card"><Icon /><p>{label}</p><b>{value}</b></article>; }
function Orders({ orders, setSelected, busy, patch }: { orders: Order[]; setSelected: (order: Order) => void; busy: string; patch: (id: number, status: Status) => void }) { return <div className="orders-table">{orders.length ? orders.map((order) => <div className="order-row" key={order.id}><button className="order-ref" onClick={() => setSelected(order)}><b>{order.reference}</b><small>{new Date(order.createdAt).toLocaleDateString("fr-FR")} · {order.customerName}</small></button><span>{order.zone.name}</span><b>{money(order.total)}</b><select className={`status ${order.status.toLowerCase()}`} disabled={busy.includes(`/orders/${order.id}`)} value={order.status} onChange={(event) => patch(order.id, event.target.value as Status)}>{statuses.map((status) => <option key={status} value={status}>{labels[status]}</option>)}</select></div>) : <p className="admin-empty">Aucune commande pour le moment.</p>}</div>; }
